steps:
  - label: "build"
    command: ".buildkite/scripts/build.sh"
    plugins:
      - docker#v3.3.0:
          image: "golang:1.14.3-buster"
          always-pull: true
          propagate-environment: true
          shell: ["/bin/bash", "-e", "-c"]
