steps:
- label: ":build: Build"
  command: make
  timeout_in_minutes: 15
  plugins:
    - docker#v3.3.0:
        image: "golang:1.14.3-buster"
        always-pull: true
        propagate-environment: true
        shell: ["/bin/bash", "-e", "-c"]
        environment:
          - DATADOG_API_KEY
          - DATADOG_APP_KEY
          - SLACK_API_TOKEN
- label: ":lint: Lint"
  command: echo "lint"
  timeout_in_minutes: 15
  plugins:
    - docker#v3.3.0:
        image: "ubuntu:18.04"
        always-pull: true
        propagate-environment: true
        shell: ["/bin/bash", "-e", "-c"]
        environment:
          - DATADOG_API_KEY
          - DATADOG_APP_KEY
          - SLACK_API_TOKEN
