steps:
  - label: ":hammer: Example Script"
    command: "go version"
    timeout_in_minutes: 15
    plugins:
      - docker#v3.3.0:
          image: "golang:1.14.3-buster"
          always-pull: true
          propagate-environment: true
          shell: ["/bin/bash", "-e", "-c"]

#  - label: ":lint-roller: Run Linting"
#    command: "echo 'lint'"
#    timeout_in_minutes: 15
#    plugins:
#      - docker#v3.3.0:
#          image: "ubuntu:18.04"
#          always-pull: true
#          propagate-environment: true
#          shell: ["/bin/bash", "-e", "-c"]
